feat: rename to CTIS survey results
cmu-delphi/www-covidcast pull request #971
Opened 2021-07-01 07:19 UTC by sgratzl

**Prerequisites**:

- [x] Unless it is a hotfix it should be merged against the `dev` branch
- [x] Branch is up-to-date with the branch to be merged with, i.e. `dev`
- [x] Build is successful
- [x] Code is cleaned up and formatted

### Summary

rename survey results page

2021-07-01 13:29 UTC, krivard commented
Also the overview page

![image](https://user-images.githubusercontent.com/1158666/124132503-e3dabe80-da4e-11eb-8450-75603437d5ab.png)

2021-07-01 14:31 UTC, sgratzl commented
> Also the overview page

good catch I was just focusing on the survey results page

2021-07-01 14:56 UTC, krivard approved these changes
I'm set, but I'm looping Wichada in to see if there's anything we missed. Wichada you should be okay to just look at the preview link from the netlify comment above

2021-07-06 16:22 UTC, capnrefsmmat requested changes
One suggested change. Also, where do I go now to update the signal description text so it mentions the name directly?

2021-07-06 16:22 UTC, capnrefsmmat commented on src/modes/landing/Landing.svelte
> +        The Trends and Impact Survey (CTIS) offers insights into public sentiment on:
```suggestion
        The COVID Trends and Impact Survey (CTIS) offers insights into public sentiment on:
```

2021-07-06 16:24 UTC, sgratzl commented
> Also, where do I go now to update the signal description text so it mentions the name directly?

so far still at https://docs.google.com/document/d/1J36nedP6eufeRE3TbyT_BK-ofE5d18kLif2UmORkYDU/edit#

2021-07-06 16:24 UTC, sgratzl commented
and https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit#heading=h.oxebzdy7nl8w

2021-07-06 21:44 UTC, capnrefsmmat requested changes
Turns out we want to include -19 in the name

2021-07-06 21:44 UTC, capnrefsmmat commented on src/modes/landing/Landing.svelte
> +        The COVID Trends and Impact Survey (CTIS) offers insights into public sentiment on:
```suggestion
        The COVID-19 Trends and Impact Survey (CTIS) offers insights into public sentiment on:
```

2021-07-06 21:44 UTC, capnrefsmmat commented on src/modes/survey-results/SurveyResults.svelte
> +      <h2>COVID Trends and Impact Survey (CTIS) <span>Results</span></h2>
```suggestion
      <h2>COVID-19 Trends and Impact Survey (CTIS) <span>Results</span></h2>
```

2021-07-06 21:46 UTC, capnrefsmmat commented
I've also suggested a change in the dashboard config doc (mentioning the name)

2021-07-09 16:47 UTC, capnrefsmmat approved these changes
Looks good

2021-07-09 19:31 UTC, merged